---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nsm-system

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nsmgr?ref=6cb851e2075646d8476d01f4f881a9a27b80f507
- https://github.com/networkservicemesh/deployments-k8s/apps/forwarder-vpp?ref=6cb851e2075646d8476d01f4f881a9a27b80f507
- https://github.com/networkservicemesh/deployments-k8s/apps/registry-k8s?ref=6cb851e2075646d8476d01f4f881a9a27b80f507
- https://github.com/networkservicemesh/deployments-k8s/apps/registry-proxy-dns?ref=6cb851e2075646d8476d01f4f881a9a27b80f507
- https://github.com/networkservicemesh/deployments-k8s/apps/nsmgr-proxy?ref=6cb851e2075646d8476d01f4f881a9a27b80f507
- https://github.com/networkservicemesh/deployments-k8s/apps/admission-webhook-k8s?ref=6cb851e2075646d8476d01f4f881a9a27b80f507

patchesStrategicMerge:
- patch-nsmgr-proxy.yaml
- patch-registry-proxy-dns.yaml
- patch-registry.yaml

resources:
  - namespace.yaml
