---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=dbf026c78b623f99dd8e70a975fa22a68c77b393
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=dbf026c78b623f99dd8e70a975fa22a68c77b393

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
