#apiVersion: v1
#kind: Service
#metadata:
#  name: alpine
#  labels:
#    app: alpine
#    service: alpine
#spec:
#  selector:
#    app: alpine
#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: alpine-service-account
#  labels:
#    account: alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-v1
  labels:
    app: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
        sidecar.istio.io/inject: "true"
      annotations:
#        networkservicemesh.io: kernel://my-vl3-network@my.cluster1/nsm-1?dnsName=client
        networkservicemesh.io: kernel://my-vl3-network/nsm-1
    spec:
      containers:
        - name: alpine
          image: alpine:3.15.0
          imagePullPolicy: IfNotPresent
          stdin: true
          tty: true
#        - args:
#            - proxy
#            - sidecar
#            - --domain
#            - $(POD_NAMESPACE).svc.cluster.local
#            - --proxyLogLevel=warning
#            - --proxyComponentLogLevel=misc:error
#            - --log_output_level=default:info
#            - --concurrency
#            - "2"
#          env:
#              - name: JWT_POLICY
#                value: third-party-jwt
#              - name: PILOT_CERT_PROVIDER
#                value: istiod
#              - name: CA_ADDR
#                value: istio-cp.my-vl3-network:15012
#              - name: POD_NAME
#                valueFrom:
#                  fieldRef:
#                    apiVersion: v1
#                    fieldPath: metadata.name
#              - name: POD_NAMESPACE
#                valueFrom:
#                  fieldRef:
#                    apiVersion: v1
#                    fieldPath: metadata.namespace
#              - name: INSTANCE_IP
#                valueFrom:
#                  fieldRef:
#                    apiVersion: v1
#                    fieldPath: status.podIP
#              - name: SERVICE_ACCOUNT
#                valueFrom:
#                  fieldRef:
#                    apiVersion: v1
#                    fieldPath: spec.serviceAccountName
#              - name: HOST_IP
#                valueFrom:
#                  fieldRef:
#                    apiVersion: v1
#                    fieldPath: status.hostIP
#              - name: PROXY_CONFIG
#                value: |
#                  {}
#              - name: ISTIO_META_POD_PORTS
#                value: |-
#                  [
#                  ]
#              - name: ISTIO_META_APP_CONTAINERS
#                value: alpine
#              - name: ISTIO_META_CLUSTER_ID
#                value: Kubernetes
#              - name: ISTIO_META_INTERCEPTION_MODE
#                value: REDIRECT
#              - name: ISTIO_META_WORKLOAD_NAME
#                value: alpine
#              - name: ISTIO_META_OWNER
#                value: kubernetes://apis/apps/v1/namespaces/default/deployments/alpine
#              - name: ISTIO_META_MESH_ID
#                value: cluster.local
#              - name: TRUST_DOMAIN
#                value: cluster.local
#          image: docker.io/istio/proxyv2:1.14.3
#          imagePullPolicy: IfNotPresent
#          name: istio-proxy
#          volumeMounts:
#            - mountPath: /var/run/secrets/istio
#              name: certs
#          ports:
#            - containerPort: 15090
#              name: http-envoy-prom
#              protocol: TCP
#          readinessProbe:
#              failureThreshold: 30
#              httpGet:
#                path: /healthz/ready
#                port: 15021
#                scheme: HTTP
#              initialDelaySeconds: 1
#              periodSeconds: 2
#              successThreshold: 1
#              timeoutSeconds: 3
#          resources:
#              limits:
#                cpu: "2"
#                memory: 1Gi
#              requests:
#                cpu: 100m
#                memory: 128Mi
#      initContainers:
#        - args:
#            - istio-iptables
#            - -p
#            - "15001"
#            - -z
#            - "15006"
#            - -u
#            - "1337"
#            - -m
#            - REDIRECT
#            - -i
#            - '*'
#            - -x
#            - ""
#            - -b
#            - '*'
#            - -d
#            - 15090,15021,15020
#          image: docker.io/istio/proxyv2:1.14.3
#          imagePullPolicy: IfNotPresent
#          name: istio-init
#          resources:
#            limits:
#              cpu: "2"
#              memory: 1Gi
#            requests:
#              cpu: 100m
#              memory: 128Mi
#          securityContext:
#            allowPrivilegeEscalation: false
#            capabilities:
#              add:
#                - NET_ADMIN
#                - NET_RAW
#              drop:
#                - ALL
#            privileged: false
#            readOnlyRootFilesystem: false
#            runAsGroup: 0
#            runAsNonRoot: false
#            runAsUser: 0
