---
apiVersion: v1
kind: Service
metadata:
  name: greeting
  labels:
    app: greeting
    service: greeting
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: greeting
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: cert-file
data:
  ca-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIFSzCCAzOgAwIBAgIJAISwmbtxw31CMA0GCSqGSIb3DQEBBQUAMCIxDjAMBgNV
    BAoMBUlzdGlvMRAwDgYDVQQDDAdSb290IENBMB4XDTIyMDkwNzA4NTE1MVoXDTI0
    MDkwNjA4NTE1MVowPTEOMAwGA1UECgwFSXN0aW8xGDAWBgNVBAMMD0ludGVybWVk
    aWF0ZSBDQTERMA8GA1UEBwwIY2x1c3RlcjEwggIiMA0GCSqGSIb3DQEBAQUAA4IC
    DwAwggIKAoICAQDAUaweoqPHtW8eaEJtfPZuWJ4Tvr4DPgzHMGJ5GCpwnrWUufbv
    hxOU6x6II00SyYTihBeWU29tyC3ruTmRd1anTTdM36OqrItr36Pv1Eguj+PCuY6e
    55Ej0YJz+wI/+budxxLuPhqTFNCCCwANK+W9hyq2aT5SayzypU5v9akN3Pkc4NdX
    Jxf3lK1L5alHtdeLjiXF2MI0t8DB4apNiZwZp9OR0v7rDYrNZ26X8FNm38qvEa8K
    nTW3Z4UjHcNJyTo4Pa04Iz0iEO5eRBTeBX7yq9gorZnh5NkcOgZgnpd/e83fYUXD
    oiVsa+TBUZ83yae2QiT74QKkXKBeOpRX1Q02e97/Vi+9nHN8Jz/jzuLNVv/21hu0
    /nuwGnWeM3MGrZSrgC6fTbCr4UgqCDOkAKImyWHTlx6Yo2KJ8SeYiFNfKOC+fFh/
    45dS21JFWBebfFoadp7OlZSyVTPNkU4djpSvcIxdI290UggQPHJYmoVQYUTmXH+C
    nG/cncOteMifP6b8SSXrU3ADOivhz8V1SROnWKgORVncj5G2OLf9GVFhYW4vmykU
    7miIMWa/yix8yiqIClEoKYIs6rA3rmz7QhhOBAUTNgpZFaiqkuUomgaHeosCHlwE
    TLzbN3OYJawhUdu+WngmXekv/OpiYdJscNz0ntuOfG9sTEvDdHbBRDRToQIDAQAB
    o2kwZzAdBgNVHQ4EFgQUd03x4EG+2yPWkPbuxOu3UagxfNQwEgYDVR0TAQH/BAgw
    BgEB/wIBADAOBgNVHQ8BAf8EBAMCAuQwIgYDVR0RBBswGYIXaXN0aW9kLmlzdGlv
    LXN5c3RlbS5zdmMwDQYJKoZIhvcNAQEFBQADggIBAFsHmu0ivLs69ck/RrFaPbHN
    nrq1q4FRPnvY8zLgSHSvnZuQ9LqLiGBoSncL0stxJfgq+UzXn5u8Ot+9KloZ4zuS
    X39r+dCF9xHAWpivWHpmTOcbZdxzESnqt/nloVAqU3bEk/hHQXFuwMKjWuk6QMwD
    EnO2SCdIKk1vTfe88WV5ZsYe74DsYGl5kfxBHMe86zcwBqKNK9dlo6NWSus/EvSG
    Dt5pQt0dt7w5ToJAaTa+IZx34a0jh5PGzthyDXUJH4l1lkkxaT0F+yYG9WYZfrYd
    IQ53WWzMHzgJcfZUUXgqQ4zylHAAAtCUc8Ri1U79hjO0ePyQpTyPWqViPAE8QGVV
    nOFllznKxMam5d8DOiL6ENQ1IW+mlVUvhOIKxCR603nG2LRsumElr/QagQAaIa8T
    Na7dhFEOgQINCO/i4oHhST2JMxuse6B5hXCnCC54b+PPjLq2tTjHd3xIuQai2Iys
    LtZpkrEepYs5LyqkhDf3eyPX4rMxuZr+F3y+l5nSpdlmdXRQ+U4QJreIL760Z86c
    E5RHmCMt1w/1NCiMIo8DKKTxr1s1kaRIW/Q9cqphpF2sDtqNd2OsutnTeNEgnhuX
    Awc1K8Bv+CZyUxbhbV2eDtA2LQAgNgEj+RXZCz8YuHG6ZiFQZ6JnBdLPaF2iuZRv
    uP3o7hpe33QKQU8HJ2yf
    -----END CERTIFICATE-----
#  root-cert.pem: |
#    -----BEGIN CERTIFICATE-----
#    MIIFCTCCAvGgAwIBAgIJAPqxbgOa66niMA0GCSqGSIb3DQEBBQUAMCIxDjAMBgNV
#    BAoMBUlzdGlvMRAwDgYDVQQDDAdSb290IENBMB4XDTIyMDkwNzA4NTExNFoXDTMy
#    MDkwNDA4NTExNFowIjEOMAwGA1UECgwFSXN0aW8xEDAOBgNVBAMMB1Jvb3QgQ0Ew
#    ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC8XHsVguKnqX1aw6p1L2Jy
#    nD4aEFZd8o9smDMxu1DvFxIy9ZRyzevUIb5Ml0dTjbuoXCM7A2fI4vG3BR1GAJ2S
#    C+gJnEQtj/sGMLety5qVrzrYWqzPUrjSz/D4gMD8tvLW++k1Cj+7vpKuKYZOt9U5
#    t64iEkMOJy+3nTjVV1lZVFfbSkSvTPsj8BGq34X86db65fhTy4E9N6TfzRrqPYVO
#    vs+A4jIVhdzt4B5ZiAKCO1MwCnR0qELkgQSSMW0GBYoOO9j2NBXjkABhVPcaoFzj
#    LfvKOF7oEpD0Qr7Vw4XMfrPcXbnSi++Jh60nNQtM3l0PcEOEjpwHCOBaAhYgL3fA
#    Bfi6CVAKIw9YqZ4hGAMyuCRhGrEOSg/n+VJKULQ/TrsMwruDndo4fXRbZxc2GOHH
#    b3miQaJD0R0/4xmV8+HcRKz6boqzXbdidgGRAbMc8RZoyUUy8pyF6FreXwsRpcI0
#    HzmWKhSswEdFwSY2nSdI1t85Ybn30eSuiFuUZkzKPWJCVreNgOhqwuxJt2Tg0ja7
#    JWYuz9brUKTvMnKyYitED1ZgnKwUjibGrr9SgyRERZsTU4bcLbh8B1d+TKqqyebE
#    fc4y4/03/TyfDkX5sSwdlsFjthTqyxU3MIKtn+oXH9dgP7Ns2/j9ZzEayfsudwsT
#    EGbnhcfCSKaUF2b/d7zfbQIDAQABo0IwQDAdBgNVHQ4EFgQUhE3l0Jwqv1+8j46g
#    0WfFbZ2ZndgwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAuQwDQYJKoZI
#    hvcNAQEFBQADggIBAEz0C1OET3BiJDIAbjddR5oxqrL/6qrYRnuRX9ov83WRMv4T
#    dPuF9Nh875u2QAm7ILu6of17p4iUsBEdRfQy6M28bstAW4G4X0PABoiD1XTU8wvb
#    DKSOQyFFmasbqV6ipIWL8JYi3+/JIHnVYHCzlxOUJtunqgSNSb0Lgf4e+9JooKLX
#    hTx1NImxJ3ovMFNccOk884BUEBTAo9KqTk5hxnKV5EaZc/UVP34qi5uLT6rukPLm
#    Iqw3wraK+Zz2uZfIfS+jL3raGspq1571qA+tJb+jFDqyRRZU4DFfbN69sIFqmRlv
#    0ORDQfIGhDnxbklZmRZodyWGGYrL8uaMC2tDSJ2vDdx3emzJHS+fOWROhaHG1gMN
#    bDLe3g9Q1M7kZ5gDLCI+K8IxHUClY73AJgEWrBAIFe683Lu0dZBGbH6T73k4iMRo
#    cUofhorQM4NPE5hLDkonsZz8ZtU5iK06xsqZ8FPSK+Gt0Vae04myCUk9j8ZrMxcT
#    +rNnxczYeyKS5tTilGnYPqaL5EMNIikt8OlSupZb2/c5fOXlaqP6k9q4kfDdwIXL
#    bY4z7KOWBMIPziG+18DfCu/YbhxvxEYbl9BlH5ybQVrPdA412BLdF/qnybOOq3ms
#    dbBq50Wdu9l/9b3UKJoYJaaFsYUrW/fZ18GmUJJIddSCy0UHVeLs9CR9sYq1
#    -----END CERTIFICATE-----
  root-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIC/TCCAeWgAwIBAgIRAKi96pny8Nj5DdBorscAlpcwDQYJKoZIhvcNAQELBQAw
    GDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDAeFw0yMjEwMDUwODI0MTZaFw0zMjEw
    MDIwODI0MTZaMBgxFjAUBgNVBAoTDWNsdXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQDVP9ddeUmkSx5m1B77PqoLyoIhFqovmCyFYvDw
    bjO4mfbGBt9XOK4nbqlHCIb2DNcs1G7WkKRE4X6p0NMH7xNyigQVCta1hqCcRxda
    SB3wFZkiGE3yVAjR4/Jgvmhm4edL3Kp89Gb+zKVbymwyy8A8QSx280AyREWmALZ0
    cBoCE0JtHwX1jg0YUkESSOn7Fc0HOFmphjRG/4UpYWNNRlImEYrojsBa6pT6loIV
    scKdLze6IkXHusT2NzxJGgdXOXZI+JUtuKkatfz6JSJx/Gr2gAUS4pCO+TywWTuk
    tvg3CkyBn+kz2A2r50khk/Uuv+CvBBWddfBIi1+qHUMhl2EXAgMBAAGjQjBAMA4G
    A1UdDwEB/wQEAwICBDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSVGDq31Dz+
    vYkLF25eCuxgoI1IoDANBgkqhkiG9w0BAQsFAAOCAQEADUye/WUyJ57SClo7aEWQ
    HObzqY+kRo/UuH4u6bDbYymdDPHSguh3bBMgQH7Z8O5W6e725honGbGGXnJjTKW1
    C6nLerQxI7mEZSpny2kizJxwRApC9n6/MWPMwKDB1w0sZsbytBkojks7SN70jJUc
    fHOC45WX+7SQbYAb92GQBp93kqw1YqBem1dsrioaK3ZMht15R6Dj0Zu3flplLLgW
    rxRDtMkm1KhavSMZP+HgQynpjKcxSDhbEuHTbeWwiE1uxdFbUGpxDveYzjnjebxx
    o03q9QkZebbRfrdOic6rOmRwKuwGPeIlN+P2KEK2SyHWEyv37SGQFppjsaI0gUXN
    Eg==
    -----END CERTIFICATE-----
  cluster.env: |
    CANONICAL_REVISION='latest'
    CANONICAL_SERVICE='vmapp'
    ISTIO_INBOUND_PORTS='*'
    ISTIO_LOCAL_EXCLUDE_PORTS='22,15090,15021,15020'
    ISTIO_METAJSON_LABELS='{"app":"vmapp","service.istio.io/canonical-name":"vmapp","service.istio.io/canonical-revision":"latest"}'
    ISTIO_META_CLUSTER_ID='Kubernetes'
    ISTIO_META_DNS_CAPTURE='true'
    ISTIO_META_MESH_ID=''
    ISTIO_META_NETWORK=''
    ISTIO_META_WORKLOAD_NAME='vmapp'
    ISTIO_NAMESPACE='istio-vm'
    ISTIO_SERVICE='vmapp.istio-vm'
    ISTIO_SERVICE_CIDR='*'
    POD_NAMESPACE='istio-vm'
    SERVICE_ACCOUNT='serviceaccount'
    TRUST_DOMAIN='cluster.local'
  istio-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkljSG9wc2tpWnhxZzFxSzJscVJMN044NDU5Zzdibi13Y1BrVVkxWkRQeG8ifQ.eyJhdWQiOlsiaXN0aW8tY2EiXSwiZXhwIjoxNjY0OTYyMTAwLCJpYXQiOjE2NjQ5NTg1MDAsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJpc3Rpby12bSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJzZXJ2aWNlYWNjb3VudCIsInVpZCI6ImFiYTdhNTUxLTFhZDUtNDU5Ny1hNDNhLTVmYjQxMmNhNTZmOSJ9fSwibmJmIjoxNjY0OTU4NTAwLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6aXN0aW8tdm06c2VydmljZWFjY291bnQifQ.k11zs40XyEr1vHS6-kTBLrjSs-pyCNKFC76oqArnRE80qZLiTXZPc83Bir2KVM-cMsaykVrzziz3OJ96w80dBUKkLV9uhOabU7ipaBOeRyNrVEGSnLB8Tsw7-eOmti6UYoNQHmg-8LHB-WjNUcdyHZG4_Ll_QRNqZbC8DNIqM30vTcg6jyfdD1HWBH1oCtZBrxYTBmQPX0oEgIFMTt_zhIwv5KOXq4ULkEN6fyL258MJM2aBLQuyUe45QZ7qX5lx2AjZx8uIF8VD2T_GRt_qp9YJCeE7K6HWpMyp_b6LgBoMaH48OkiG_IbqJUS6smMq_4PrWERIAtXnAFsPqAX9Xg
  mesh: |
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      proxyMetadata:
        CANONICAL_REVISION: latest
        CANONICAL_SERVICE: vmapp
        ISTIO_META_CLUSTER_ID: Kubernetes
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_MESH_ID: ""
        ISTIO_META_NETWORK: ""
        ISTIO_META_WORKLOAD_NAME: vmapp
        ISTIO_METAJSON_LABELS: '{"app":"vmapp","service.istio.io/canonical-name":"vmapp","service.istio.io/canonical-revision":"latest"}'
        POD_NAMESPACE: istio-vm
        SERVICE_ACCOUNT: serviceaccount
        TRUST_DOMAIN: cluster.local
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: greeting-sa
  labels:
    account: greeting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
  labels:
    app: greeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
      annotations:
#        networkservicemesh.io: kernel://my-vl3-network/nsm-1?dnsName=server
#        networkservicemesh.io: kernel://my-vl3-network@my.cluster1/nsm-1
    spec:
      volumes:
        - name: cert
          configMap:
            name: cert-file
#            items:
#              - key: root-cert.pem
#                path: root-cert.pem
      serviceAccountName: greeting-sa
      containers:
        - name: server
          image: hashicorp/http-echo:alpine
          args:
            - -text="hello world from istio"
            - -listen=:9080
          ports:
            - containerPort: 9080
              name: http
        - args:
            - proxy
            - sidecar
#            - --domain
#            - $(POD_NAMESPACE).svc.cluster.local
#            - --proxyLogLevel=warning
#            - --proxyComponentLogLevel=misc:error
#            - --log_output_level=default:info
#            - --concurrency
#            - "2"
          env:
#              - name: CA_ROOT_CA
#                value: /etc/ca-cert.pem
              - name: CONTROL_PLANE_AUTH_POLICY
                value: NONE
              - name: JWT_POLICY
                value: third-party-jwt
              - name: PILOT_CERT_PROVIDER
                value: NONE
              - name: CA_ADDR
                value: 10.244.1.2:15012
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
              - name: POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
              - name: INSTANCE_IP
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: status.podIP
              - name: SERVICE_ACCOUNT
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: spec.serviceAccountName
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: status.hostIP
              - name: PROXY_CONFIG
                value: |
                  {}
              - name: ISTIO_META_POD_PORTS
                value: |-
                  [
                  ]
              - name: ISTIO_META_APP_CONTAINERS
                value: alpine
              - name: ISTIO_META_CLUSTER_ID
                value: Kubernetes
              - name: ISTIO_META_INTERCEPTION_MODE
                value: REDIRECT
              - name: ISTIO_META_WORKLOAD_NAME
                value: alpine
              - name: ISTIO_META_OWNER
                value: kubernetes://apis/apps/v1/namespaces/default/deployments/alpine
              - name: ISTIO_META_MESH_ID
                value: cluster.local
              - name: TRUST_DOMAIN
                value: cluster.local
          image: docker.io/istio/proxyv2:1.14.3
          imagePullPolicy: IfNotPresent
          name: istio-proxy
          volumeMounts:
            - mountPath: /var/run/secrets/istio/root-cert.pem
              name: cert
              subPath: root-cert.pem
            - mountPath: /var/lib/istio/envoy/cluster.env
              name: cert
              subPath: cluster.env
            - mountPath: /etc/istio/config/mesh
              name: cert
              subPath: mesh
            - mountPath: /var/run/secrets/tokens/istio-token
              name: cert
              subPath: istio-token
          ports:
            - containerPort: 15090
              name: http-envoy-prom
              protocol: TCP
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz/ready
              port: 15021
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
      initContainers:
        - args:
                  - istio-iptables
                  - -p
                  - "15001"
                  - -z
                  - "15006"
                  - -u
                  - "1337"
                  - -m
                  - REDIRECT
                  - -i
                  - '*'
                  - -x
                  - ""
                  - -b
                  - '*'
                  - -d
                  - 15090,15021,15020
          image: docker.io/istio/proxyv2:1.14.3
          imagePullPolicy: IfNotPresent
          name: istio-init
          resources:
            limits:
                cpu: "2"
                memory: 1Gi
            requests:
                cpu: 100m
                memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW
                drop:
                  - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
