---
apiVersion: v1
kind: Service
metadata:
  name: greeting
  labels:
    app: greeting
    service: greeting
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: greeting
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: cert-file
data:
  root-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIC/DCCAeSgAwIBAgIQXGjWogSiT86PxcaTpCjhYzANBgkqhkiG9w0BAQsFADAY
    MRYwFAYDVQQKEw1jbHVzdGVyLmxvY2FsMB4XDTIyMTAyMDA4NTU0N1oXDTMyMTAx
    NzA4NTU0N1owGDEWMBQGA1UEChMNY2x1c3Rlci5sb2NhbDCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBAM9oXw0EkQ8V021oPnfXnaswQb1gOkGpwxr7zzBL
    xe9a9F/noyoFapj/ZaqVRmDvL17ALFfTdBxgY9r2RJL6N5tWs9mvJJJUoubykbbZ
    eq725G0jqZKihFhCOfrhwrpMfDASE5wYnH0N0xEYI/Ps+2lexxaD3lXoA8uuz+Yh
    LB4TXo4d7tCHWRQXgmhf9DNt2CU9s+K9uyp66/Byd0Wi3h+nFIsFij/+QRF72KQ+
    iftjXDcO1NU+eAllhsEKPk8qWYK0O6kE17EkZL/XLh1E26ohc+7OKRpoWwiLIHM0
    xFkLOURHKHvsFR5zZFkj/QImejP0qPwSayiuVQ6MEExKPZMCAwEAAaNCMEAwDgYD
    VR0PAQH/BAQDAgIEMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFOgvDy6IC8Zu
    uz28HKJogFGxL0uTMA0GCSqGSIb3DQEBCwUAA4IBAQDOQkApctGg0/BYJB2FTecd
    UbYfJnPgDDMWZZxxySPiM5mApJTHNZxG/d9b5RmEVCu8h7BNviPSbQs/3knem1/u
    oI3iPtpcnowGMca9WidzvCQuHgQwqPs4mpYWpg8Ylt+UP1ylUVMnm1hTm0sYdwtn
    g6X1dqeAUuiOJaYIUCTGRZ3dX21IpRivZ/kPk1DSU+UFWyspKdnM3zW5KuGfNWEx
    +eEGNBJEmEcsMP7zoNDK5g2PkLWnH6xazT8NVFzEqpmvpso1fgYil460fMXCUkiI
    4kjH+uew8kugmIKWFwZkFRTzcpi30E6IlsxlTpmrxxe+l0j8ql31I5/Cc5QEFYjh
    -----END CERTIFICATE-----
  cluster.env: |
    CANONICAL_REVISION='latest'
    CANONICAL_SERVICE='vm-app'
    ISTIO_INBOUND_PORTS='*'
    ISTIO_LOCAL_EXCLUDE_PORTS='22,15090,15021,15020'
    ISTIO_METAJSON_LABELS='{"app":"vm-app","service.istio.io/canonical-name":"vm-app","service.istio.io/canonical-revision":"latest"}'
    ISTIO_META_CLUSTER_ID='Kubernetes'
    ISTIO_META_DNS_CAPTURE='true'
    ISTIO_META_MESH_ID='mesh1'
    ISTIO_META_NETWORK=''
    ISTIO_META_WORKLOAD_NAME='vm-app'
    ISTIO_NAMESPACE='vm-ns'
    ISTIO_SERVICE='vm-app.vm-ns'
    ISTIO_SERVICE_CIDR='*'
    POD_NAMESPACE='vm-ns'
    SERVICE_ACCOUNT='serviceaccountvm'
    TRUST_DOMAIN='cluster.local'
  istio-token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ikk3VUVLVkJvT3B6Xzk4SDhCNldaS1ZRWnZoUTZhcmhyRU5nSmEtR0xMTTAifQ.eyJhdWQiOlsiaXN0aW8tY2EiXSwiZXhwIjoxNjY2MjU5ODIxLCJpYXQiOjE2NjYyNTYyMjEsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJ2bS1ucyIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJzZXJ2aWNlYWNjb3VudHZtIiwidWlkIjoiMWMwMTUzNjEtNGY2Ny00ZTI3LTg3ZDMtYzQ2OGU1ZDY4Y2FhIn19LCJuYmYiOjE2NjYyNTYyMjEsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDp2bS1uczpzZXJ2aWNlYWNjb3VudHZtIn0.y67C2uCd38UH58MhBeipTGVS3J-hHYQtyI9fS8rSfjX3l4iOgIZ0tQUM2nN1_ZynEco9TxBdQckByGNz6_gwXWMLOSq2M63qkJoyUwQ9Qhm6uyioeS9h5a0BPycv2jQpFOXGEVViQANLhl0xPW6P8QwaGCDU-sHZJsKYxxc-JTO2XUDeik1UA1xEtBfQLUn03amSpbiDTkABKOznVg85Qb3jMzMf34zH4ufOku5YarP2PSPyn5ZE2hQr4A5N9b7HgShqcW1Z_hJIxpyn49vHaYgKUEeRgpbFoku3CrwseecwUxzVTFbCO8qO-6isdUShLLjf1k1I3hU5-3AZWUQf4w
  mesh: |
    defaultConfig:
      discoveryAddress: 172.18.0.3:30398
      meshId: mesh1
      proxyMetadata:
        CANONICAL_REVISION: latest
        CANONICAL_SERVICE: vm-app
        ISTIO_META_CLUSTER_ID: Kubernetes
        ISTIO_META_DNS_CAPTURE: "true"
        ISTIO_META_MESH_ID: mesh1
        ISTIO_META_NETWORK: ""
        ISTIO_META_WORKLOAD_NAME: vm-app
        ISTIO_METAJSON_LABELS: '{"app":"vm-app","service.istio.io/canonical-name":"vm-app","service.istio.io/canonical-revision":"latest"}'
        POD_NAMESPACE: vm-ns
        SERVICE_ACCOUNT: serviceaccountvm
        TRUST_DOMAIN: cluster.local
      serviceCluster: vm-app.vm-ns
      tracing:
        zipkin:
          address: zipkin.istio-system:9411
#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: greeting-sa
#  labels:
#    account: greeting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
  labels:
    app: greeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
      annotations:
#        networkservicemesh.io: kernel://my-vl3-network/nsm-1?dnsName=server
#        networkservicemesh.io: kernel://my-vl3-network@my.cluster1/nsm-1
    spec:
      volumes:
        - name: cert
          configMap:
            name: cert-file
#            items:
#              - key: root-cert.pem
#                path: root-cert.pem
#      serviceAccountName: greeting-sa
      containers:
        - name: server
          image: hashicorp/http-echo:alpine
          args:
            - -text="hello world from istio"
            - -listen=:9080
          ports:
            - containerPort: 9080
              name: http
        - args:
            - proxy
            - sidecar
            - --domain
            - ""
            - --proxyLogLevel=warning
            - --proxyComponentLogLevel=misc:error
            - --log_output_level=default:debug
            - --concurrency
            - "0"
          env:
#              - name: CA_ROOT_CA
#                value: /etc/ca-cert.pem
#              - name: CONTROL_PLANE_AUTH_POLICY
#                value: NONE
              - name: JWT_POLICY
                value: third-party-jwt
              - name: PILOT_CERT_PROVIDER
                value: NONE
              - name: CA_ADDR
                value: 172.18.0.3:30398
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
              - name: POD_NAMESPACE
                value: vm-ns
#              - name: INSTANCE_IP
#                valueFrom:
#                  fieldRef:
#                    apiVersion: v1
#                    fieldPath: status.podIP
              - name: SERVICE_ACCOUNT
                value: serviceaccountvm
              - name: HOST_IP
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: status.hostIP
              - name: PROXY_CONFIG
                value: |
                  {}
              - name: ISTIO_META_POD_PORTS
                value: |-
                  [
                  ]
              - name: ISTIO_META_APP_CONTAINERS
                value: alpine
              - name: ISTIO_META_CLUSTER_ID
                value: Kubernetes
              - name: ISTIO_META_INTERCEPTION_MODE
                value: REDIRECT
              - name: ISTIO_META_WORKLOAD_NAME
                value: vm-app
#              - name: ISTIO_META_OWNER
#                value: kubernetes://apis/apps/v1/namespaces/default/deployments/alpine
              - name: ISTIO_META_MESH_ID
                value: cluster.local
              - name: TRUST_DOMAIN
                value: cluster.local
          image: docker.io/istio/proxyv2:1.15.2
          imagePullPolicy: IfNotPresent
          name: istio-proxy
          volumeMounts:
            - mountPath: /var/run/secrets/istio/root-cert.pem
              name: cert
              subPath: root-cert.pem
            - mountPath: /var/lib/istio/envoy/cluster.env
              name: cert
              subPath: cluster.env
            - mountPath: /etc/istio/config/mesh
              name: cert
              subPath: mesh
            - mountPath: /var/run/secrets/tokens/istio-token
              name: cert
              subPath: istio-token
          ports:
            - containerPort: 15090
              name: http-envoy-prom
              protocol: TCP
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz/ready
              port: 15021
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
      initContainers:
        - args:
                  - istio-iptables
                  - -p
                  - "15001"
                  - -z
                  - "15006"
                  - -u
                  - "1337"
                  - -m
                  - REDIRECT
                  - -i
                  - '*'
                  - -x
                  - ""
                  - -b
                  - '*'
                  - -d
                  - 15090,15021,15020
          image: docker.io/istio/proxyv2:1.15.2
          imagePullPolicy: IfNotPresent
          name: istio-init
          resources:
            limits:
                cpu: "2"
                memory: 1Gi
            requests:
                cpu: 100m
                memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW
                drop:
                  - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
