---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=49b796b3fac61f2ca634386eb686b0ebcaee6abf
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=49b796b3fac61f2ca634386eb686b0ebcaee6abf

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
