---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v2
  labels:
    app: ratings
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v2
  template:
    metadata:
      labels:
        app: ratings
        version: v2
        sidecar.istio.io/inject: "false"
      annotations:
        networkservicemesh.io: kernel://autoscale-istio-proxy/nsm-1?app=ratings
    spec:
      containers:
      - name: ratings
        image: docker.io/istio/examples-bookinfo-ratings-v1:1.16.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8
        options:
          - name: ndots
            value: "5"
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
