---
apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  namespace: kuma-demo
  annotations:
    networkservicemesh.io: kernel://my-vl3-network@my.cluster1/nsm-1?dnsName=demo-app
  labels:
    name: app
spec:
  containers:
  - image: ubuntu
    ports:
    - containerPort: 5000
    - containerPort: 9901
    - containerPort: 15001
    command:
      - /bin/sh
      - "-c"
      - "sleep 600m"
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
