apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: "server"
  namespace: "default"
spec:
  metadata:
    labels:
      app: "server"
  template:
    serviceAccount: "service-account"
    network: ""
