---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-jaeger-and-prometheus

resources:
- client.yaml
- netsvc.yaml

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-kernel?ref=c2118bb00fb516af2903731a1d92662b5f69a7b1

patchesStrategicMerge:
- patch-nse.yaml
