---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma-control-plane
  namespace: kuma-system
spec:
  template:
    metadata:
      annotations:
        networkservicemesh.io: kernel://my-vl3-network/nsm-1?dnsName=control-plane-kuma
    spec:
      containers:
        - name: control-plane
          env:
            - name: KUMA_RUNTIME_KUBERNETES_INJECTOR_BUILTIN_DNS_ENABLED
              value: "false"
            - name: KUMA_DP_SERVER_AUTH_TYPE
              value: "none"
            - name: KUMA_API_SERVER_HTTPS_ENABLED
              value: "false"
            - name: KUMA_API_SERVER_HTTP_INTERFACE
              value: "control-plane-kuma.my-vl3-network"
