---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=1230ee64381186cef818d5c18496dae0ef2c4d5d
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=1230ee64381186cef818d5c18496dae0ef2c4d5d

resources:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/1230ee64381186cef818d5c18496dae0ef2c4d5d/examples/features/vl3-dns/nsc.yaml
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/1230ee64381186cef818d5c18496dae0ef2c4d5d/examples/features/vl3-dns/namespace.yaml

patchesStrategicMerge:
- https://raw.githubusercontent.com/networkservicemesh/deployments-k8s/1230ee64381186cef818d5c18496dae0ef2c4d5d/examples/features/vl3-dns/nse-patch.yaml
