---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v2
  labels:
    app: productpage
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v2
  template:
    metadata:
      labels:
        app: productpage
        version: v2
        sidecar.istio.io/inject: "false"
      annotations:
        networkservicemesh.io: kernel://autoscale-istio-proxy/nsm-1?app=productpage
    spec:
      containers:
      - name: productpage
        image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          runAsUser: 1000
      volumes:
      - name: tmp
        emptyDir: {}
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 8.8.8.8
        options:
          - name: ndots
            value: "5"
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
