---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=c2118bb00fb516af2903731a1d92662b5f69a7b1
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=c2118bb00fb516af2903731a1d92662b5f69a7b1

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
