---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=1f8f5b0690d0a3b7e97619e653505647bdb21727
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=1f8f5b0690d0a3b7e97619e653505647bdb21727

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
